### PR TITLE
PW-40: Last modified column on plugins page

### PR DESCRIPTION
**Pull request by SkullTech**
Add a column in the plugins table which shows how long ago the plugin was last updated.

### CODE REVIEW

**Comment by SkullTech** [comment]
I don't think it cloning the Repo would have any negative effect. It may slow down the process a little (not sure about that too, need to do some benchmarks), but otherwise wouldn't have any significant adverse effect.

And from the downloaded `.zip` file we can not get any `last_modified` data, to get that we would have to use `git clone`.
Another approach I can think of is getting the `last_modified` data from `Github API`, but that sounds like the worst idea to me.

**Comment by samj1912** [comment]
Not sure about got cloning and checking out branches. We are soon moving towards a plugin manifest based system. Metadata like this can be generated during manifest generation.

**Comment by SkullTech** [comment]
Oh yeah that would be best. But until then we could use this one. And also, can you tell me what are the drawbacks with this approach? I'm a beginner so forgive me if I'm being naive.

**Comment by zas** [comment]
> Oh yeah that would be best. But until then we could use this one. And also, can you tell me what are the drawbacks with this approach? I'm a beginner so forgive me if I'm being naive.

There's no real drawback, your implementation is rather correct. My comment was more about the fact we are moving to zip-contained plugin with a manifest file (prolly json), to get rid of python files "headers" we have now, and to ease generation and parsing of metadata associated with the plugin.

So, while your approach is technically correct, it doesn't fit well our current plans.
If you are interested in discussing the future of Picard (and its plugins) you may attend to the IRC meeting we are doing on each tuesday (#metabrainz).

**Comment by gentlecat** [comment]
@brainzbot, ok to test.

**Comment by SkullTech** [comment]
Jenkins is giving a error on the `download_plugins` function, but it runs fine on my Ubuntu machine.

```bash
sumit@sumit-HP-Pavilion-Notebook:~/Coding/picard-website/website$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from build_plugins import download_plugins
>>> print(download_plugins())
Downloading files. Please wait....
Cloning into '/tmp/tmpviY22mPICARD-WEBSITE'...
remote: Counting objects: 1965, done.
remote: Total 1965 (delta 0), reused 0 (delta 0), pack-reused 1965
Receiving objects: 100% (1965/1965), 433.32 KiB | 50.00 KiB/s, done.
Resolving deltas: 100% (975/975), done.
Checking connectivity... done.
Branch master set up to track remote branch master from origin.
Switched to a new branch 'master'
('/tmp/tmpviY22mPICARD-WEBSITE', '/tmp/tmpviY22mPICARD-WEBSITE/plugins')
>>> 
```

**Comment by zas** [comment]
Old and not updated, feel free to re-open

**Pull request closed without merging**
