### PR TITLE
Add redirection link to user guide

### PR DESCRIPTION
**Pull request by rdswift**
# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**: Add a link in the menu bar to the User Guide at https://picard-docs.musicbrainz.org

# Problem

There was no link to the User Guide on the Picard website.

* JIRA ticket (_optional_): [PW-XXX](https://tickets.metabrainz.org/browse/PW-XXX)

# Solution

Add a link.

# Action

Please review carefully.  I haven't tested this live because I don't run a copy of the website locally.

### CODE REVIEW

**Comment by rdswift** [comment]
We also need to think about which pages (if any) we no longer want to maintain on picard.mb.o (e.g.: options, scripting, tags, etc.)

**Comment by zas** [comment]
BTW, I think we should remove redundant docs (I'd prefer to point to picard-docs whenever possible), instead of maintaining 2 different documentation about the same thing, that could be misleading.

@phw @Sophist-UK

**Comment by phw** [comment]
Yes please. I'd really just link to the corresponding picard-docs pages for the duplicated docs.

**Comment by Sophist-UK** [comment]
I am personally of the view that documentation should be on one site only, either https://picard.musicbrainz.org/docs/ or https://picard-docs.musicbrainz.org/en/index.html I don't mind, whichever provides the best way of maintaining the documentation with ease of use, approval workflow etc.

**Comment by phw** [comment]
Please see my proposed changes at #202

**Comment by rdswift** [comment]
> whichever provides the best way of maintaining the documentation with ease of use, **approval workflow** etc.

(emphasis mine)

I agree.  Until now, the new documentation has been mostly in initial development mode, and I've been making changes (e.g.: corrections, additions, deletions) and re-publishing periodically without any reviews.  It was appropriate at the time to get the initial product out there, but I think that it's time to move to a more structured review and approval process.  I'm open to suggestions.

The documentation is currently built and published automatically when a change is made to the `master` branch.  I've been using the `development` branch as a staging area, collecting changes to publish periodically.  I've also been using a `next_picard_release` branch to collect the changes that have not yet been released in the stable version.  Other branches are created and deleted as required.  I'd sort of like to continue this branch configuration unless someone has a better suggestion.

From here on, I think all changes to the three main branches should be by pull request, with at least one reviewer approval before merging.  Would any of you be willing to be added to the project team for the documentation?

Should we be working towards having the documentation hosted on ReadTheDocs eventually, rather than GitHub pages?  I can look into this further, but unfortunately `picard.readthedocs.io` has already been claimed for another project, so we would need to look at something like `musicbrainz-picard.readthedocs.io` which starts to get a bit unwieldy (unless we continue using the stable `picard-docs.musicbrainz.org` and change the redirect to point to `musicbrainz-picard.readthedocs.io`).

Also, I suggest that we move the repository to `metabrainz` from `rdswift` at some point in the future.  No rush (and perhaps defer until after the long-term hosting decisions are made for the documentation itself), but something to consider.

**Comment by Sophist-UK** [comment]
@rdswift Bob - I hope that you weren't taking my comment about approval workflow as any form of criticism because I assure you none was intended. IMO it is perfectly normal for initial development of a new resource to be done as one big piece of work - my comment was about how we manage it once it has gone live. Indeed, now I have looked at it in more detail, I can see just how much work has gone into it!!!!

And having dug a little deeper, I now see that it is based on a Github repo - so workflow is pretty much taken care of.

The only comment I would make, and it is a minor one, is to provide a little more encouragement for users to contribute to improvements to the documentation with e.g. example scripts, tips and techniques etc. (but with some caveats about there being an approval process to keep quality high). I will try out the PR process and add something to the Credits and Updates page.

As and when I get time, I will give it a full read through - I suspect I will learn quite a lot!!!

P.S. I am not sure will happen once I have forked the RDSwift repo and it is moved to MusicBrainz. But I suspect the sooner it is moved the better.

**Comment by rdswift** [comment]
@Sophist-UK 

> @rdswift Bob - I hope that you weren't taking my comment about approval workflow as any form of criticism because I assure you none was intended.

And none taken.  You simply mentioned something that has been bugging me for a while now, and I used it as a springboard for my comments.  I have been playing pretty fast 'n' loose with updates and (usually) not having them reviewed before posting.  I really don't like doing that.

> The only comment I would make, and it is a minor one, is to provide a little more encouragement for users to contribute to improvements to the documentation with e.g. example scripts, tips and techniques etc. (but with some caveats about there being an approval process to keep quality high).

Excellent suggestion.  I'll start thinking about how to phrase some of that and where to include it.  Thanks.

> I will try out the PR process and add something to the Credits and Updates page.

Thank-you for that.  I look forward to any comments you may have, and suggestions for improvement.

> As and when I get time, I will give it a full read through - I suspect I will learn quite a lot!!!

Somehow I'd be surprised if there was much in there that you don't know (or knew once and had forgotten).  the document has become pretty lengthy, but I feel there's still considerable room for improvement by expanding descriptions and explanations, and by adding more examples.

Thanks again for taking a look when you have a minute here and there.  Much appreciated.

**Comment by phw** [comment]
I'll close this as we have #202 merged now

**Pull request closed without merging**
