### PR TITLE
PW-60: Add all supported formats to the FAQ

### PR DESCRIPTION
**Pull request by rahuliitg**
Fixes issue PW-60.
https://tickets.metabrainz.org/browse/PW-60
Please review and merge :)

### CODE REVIEW

**Comment by samj1912** [comment]
@brainzbot add to whitelist

**Comment by samj1912** [comment]
@brainzbot add to whitelist

**Comment by rahuliitg** [comment]
reason for unsuccessful checks ?? can't find anything from details.

**Comment by samj1912** [comment]
@brainzbot retest this please

**Comment by rahuliitg** [comment]
@samj1912 :  same problem

**Comment by samj1912** [comment]
@brainzbot retest this please

**Pull request merged**
