### PR TITLE
PW-3: Make header on index page responsive

### PR DESCRIPTION
**Pull request by phw**
# Summary

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem
The "MusicBrainz Picard" header is not responsive, so when the screen size is reduced, the text overflows from the container.

* JIRA ticket (_optional_): [PW-3](https://tickets.metabrainz.org/browse/PW-3)

# Solution
Attempt to scale cleanly on different sizes

# Action

### CODE REVIEW

**Comment by samj1912** [comment]
Doesn't pw use bootstrap? Is it absolutely necessary to use media width sizes instead of using bootstrap classes?

**Comment by phw** [comment]
I tried that but found that header to be very specific. If you want this to look good you need other breakpoints than the bootstrap defined ones

**Comment by samj1912** [comment]
Since it's a UI change, can you also post some before and after screenshots of the changes?

**Comment by zas** [comment]
> Since it's a UI change, can you also post some before and after screenshots of the changes?

@phw ^^

**Comment by phw** [comment]
Large header (same as current behavior):

bildschirmfoto vom 2018-09-02 um 11 32 12

At < 730px the font and logo get sized down a bit to not make it so massive and prevent line breaks on even smaller sizes:

bildschirmfoto vom 2018-09-02 um 11 34 07

At < 590 px:

bildschirmfoto vom 2018-09-02 um 11 36 30

At < 400 px the text size of the download button gets adjusted:

bildschirmfoto vom 2018-09-02 um 11 41 06

It still looks good even smaller:

bildschirmfoto vom 2018-09-02 um 11 42 26

**Pull request merged**
