### PR TITLE
Add information about SSL errors on Windows to FAQ

### PR DESCRIPTION
**Pull request by samj1912**
# Summary

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): [PW-XXX](https://tickets.metabrainz.org/browse/PW-XXX)

# Solution

# Action

### CODE REVIEW

**Comment by phw** [comment]
Can't we include those files in the release when we know this version works and some windows versions don't have them?

**Comment by samj1912** [comment]
I did include them in the release earlier, however that website is 3rd party and goes offline at times. Also, I would like people to download or build their own DLLs in case they want to.

**Comment by phw** [comment]
> however that website is 3rd party and goes offline at times

For me this is a reason more to include this in the release. When releasing we can just include these two files. We can even get the files from previous release if the website should not be available (or the files should actually be available on the build system anyway). But shipping the software in a state where it is known it will crash for a certain subset of users and instead of providing the fix sent the users on a quest to hunt DLLs sounds bad.

Or is there any downside of including those files?

**Comment by mineo** [comment]
Can't we put the files on ftp.musicbrainz.org and download them from there during the build? We'd need to update them when new openssl releases are made, but we also need to do that at the moment by directly linking to a specific version of the files.

**Comment by mineo** [comment]
Also, according to http://doc.qt.io/qt-5/ssl.html OpenSSL 1.0.0 from 2010 is still supported by Qt, do Windows versions really ship something older than that?

**Pull request merged**
