### PR TITLE
PW-85: Add descriptions for new scripting functions

### PR DESCRIPTION
**Pull request by rdswift**
# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [x] Other
* **Describe this change in 1-2 sentences**:  Update the scripting page to add descriptions for the new functions added in PICARD-1716, PICARD-1720 and PICARD-1721.

# Problem

New scripting functions have been added, and should be documented on the website.

* JIRA ticket: [PW-85](https://tickets.metabrainz.org/browse/PW-85)

# Solution

Added descriptions for the new functions:
* $find()
* $reverse()
* $substr()
* $getmulti()
* $foreach()
* $map()
* $while()
* $slice()
* $join()

# Action

This should not be merged until the new version of Picard containing the new functions has been released.

### CODE REVIEW

**Comment by phw** [comment]
Thanks a lot for this. Can you update your pull request to merge into the branch [picard-2.3](https://github.com/metabrainz/picard-website/tree/picard-2.3) instead of master?

We have a few other things to update, we can create separate PRs and merge them all into picard-2.3 and have a separate PR to merge this into master for the release. We did this for the last releases and it worked well :)

**Comment by rdswift** [comment]
Target changed to `picard-2.3` branch.  I should have noticed that myself.  Thanks.

**Comment by rdswift** [comment]
@phw I just noticed that your new `$iswboundary()` isn't in the scripting documentation yet.  Would you like me to add it to this PR?

**Comment by phw** [comment]
>  I should have noticed that myself.

Actually no, you couldn't :) I just added that branch just before writing the comment. I actually wanted to update the target for the PR myself, but this seems to be restricted to the creator of the PR.

> I just noticed that your new `$iswboundary()` function isn't in the scripting documentation yet.

That's actually not a scripting function on it's own. It's just a helper for the implementation of `$title`.

**Comment by phw** [comment]
I have merged the code and opened a new PR https://github.com/metabrainz/picard-website/pull/180 to track the complete set of Picard 2.3 changes.

**Pull request merged**
