### PR TITLE
Link documentation to picard-docs.musicbrainz.org

### PR DESCRIPTION
**Pull request by phw**
# Summary
Link to documentation on http://picard-docs.musicbrainz.org/

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): [PW-XXX](https://tickets.metabrainz.org/browse/PW-XXX)

# Solution
Update links to point to http://picard-docs.musicbrainz.org/. Maintain redirects for old URLs, remove unused documentation templates.

# Action

### CODE REVIEW

**Comment by phw** [comment]
In #201 I see some consensus to link to the new, more complete documentation introduced by @rdswift 

I am not 100% sure how to best deal with this on the current website, but this would be my proposal. This basically makes the navigation link point directly to picard-docs and ads redirect links so we maintain compatibility with the old links.

@rdswift @zas @Sophist-UK I'd appreciate your opinion and feedback on this.

**Comment by zas** [comment]
LGTM, apart Jenkins complaints

**Comment by phw** [comment]
@zas Fixed the tests in https://github.com/metabrainz/picard-website/pull/202/commits/16cbd9ab7d533df902f69ea7b9ff58972ceb5e8c

Now Jenkins fails differently in a way I don't fully understand

**Comment by zas** [comment]
> 
> Now Jenkins fails differently in a way I don't fully understand

I restarted the build and it passes, see https://ci.metabrainz.org/job/picard-website/472/

There was an error in previous build related to apt, prolly transient network issue.

**Comment by rdswift** [comment]
This looks good to me.  Eventually I'll have to figure out a better way for multiple language support, so we don't hard link to the English (/en/) pages.  Not really an issue until we sort out (if and) how we want to translate the documentation.

**Pull request merged**
