### PR TITLE
changelog: use markdown formatted changelog

### PR DESCRIPTION
**Pull request by phw**
# Summary
This is the server side change for converting the NEWS.md file to markdown in https://github.com/metabrainz/picard/pull/1168

The general layout of the page stays the same, including the special formatting of the version headers:

grafik

But the code is much cleaner without the need for full regex parsing. I decided to use mistune, as it is a rather fast Markdown library and easily allows to manipulate the rendering process. I use this to properly format the headlines with the same level and layout as before.

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): [PW-XXX](https://tickets.metabrainz.org/browse/PW-XXX)

# Solution

# Action

### CODE REVIEW

**Comment by phw** [comment]
@zas I messed this up a bit by merging https://github.com/metabrainz/picard/pull/1168 too early. I thought it would be good to have this merged so I can easily test my changes against the live URL, but of course this now messed up https://picard.musicbrainz.org/changelog/ . As a quick fix we could commit the old NEWS.txt  to the Picard repository again.

Apart from this we have to make sure to update `CHANGELOG_URL` in config to use the .md file when deploying this PR.

**Comment by samj1912** [comment]
The changelog on the website currently seems to be broken?

**Comment by phw** [comment]
@samj1912 Yes, this is what this PR is for, but the change is not yet deployed.

**Comment by zas** [comment]
I just deployed this new version.

Le sam. 24 août 2019 à 13:14, Philipp Wolfer <notifications@github.com> a
écrit :

**Pull request merged**
