### PR TITLE
downloads: Add GNU Guix

### PR DESCRIPTION
**Pull request by 80aff123-9163-4f3e-a93d-4a2f35af9be1**
GNU Guix is a transactional package manager and an advanced distribution of the GNU system that respects user freedom. Guix can be used on top of any system running the kernel Linux, or it can be used as a standalone operating system distribution for i686, x86_64, ARMv7, and AArch64 machines.

In addition to standard package management features, Guix supports transactional upgrades and roll-backs, unprivileged package management, per-user profiles, and garbage collection. When used as a standalone GNU/Linux distribution, Guix offers a declarative, stateless approach to operating system configuration management. Guix is highly customizable and hackable through Guile programming interfaces and extensions to the Scheme language.

# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): [PW-XXX](https://tickets.metabrainz.org/browse/PW-XXX)

# Solution

# Action

### CODE REVIEW

**Comment by ccao001** [comment]
I added the page for picard that was packaged for the guix package manager and gnu/linux distro.

Guix System is a gnu/linux distro inspired by NixOS. Its package manager guix is intended to be portable across all linux distributions.

Let me know if I should edit anything in the above.

**Review by phw — COMMENTED** [review]
Thanks a lot, I'm happy to merge this.

Just a bit concerned about the versioned link. Do you know what will happen when the Guix package gets upgraded? Will the picard-2.1.3 link lead to an empty page?

**Comment by zas** [comment]
@ccao001 2.1.3 isn't the latest stable release, how do you track releases?
What about versioned link @phw asked about in previous comment?

**Comment by ccao001** [comment]
> @ccao001 2.1.3 isn't the latest stable release, how do you track releases?
> What about versioned link @phw asked about in previous comment?

@zas 

We track releases with a tool called [guix refresh](https://guix.gnu.org/manual/en/html_node/Invoking-guix-refresh.html) that let's us know what packages are out of date.

Guix is volunteer led so probably no packager has upgraded 2.1.3 yet to 2.4.4

> What about versioned link @phw asked about in previous comment?

@phw @zas 

The versioned link will upgrade also. The current version of picard in guix is 2.1.3 unfortunately.

I'll ask in the freenode irc (#guix) today to see what is the status on that. If nobody is working on it I can try upgrading picard in guix very soon.

Here is the [guix package definition](https://github.com/guix-mirror/guix/blob/46eb357973f711b59bb1312025c9248010dc1040/gnu/packages/music.scm#L2807) for picard.

**Comment by phw** [comment]
I will close this, as this is currently not working in a way that would be useful. The link https://guix.gnu.org/en/packages/picard-2.1.3/ no longer is valid, instead it is now some other version. There seems to be no generic link that always points to the latest version.

That means any link we would add would break on updates. Furthermore, it is kind of complicated to find the proper link. The package page https://guix.gnu.org/de/packages/ does not provide any search, and finding Picard requires looking through a list of 33 pages for all packages starting with P. 

I'm happy to add a link to Guix, but that's only possible if there is a stable link to link to. How this can work can be seen here:

https://depot.haiku-os.org/picard

That link always points to the latest version of the picard package for Haiku. It doesn't change, it doesn't get invalid. It will resolve to the proper version, e.g.

https://depot.haiku-os.org/#!/pkg/picard/haikuports/2/6/1/-/1/x86_64

**Pull request closed without merging**
