### PR TITLE
Add tagger script syntax highlighting using highlight.js

### PR DESCRIPTION
**Pull request by phw**
This pull request adds syntax highlighting for tagger script to the scripting page. It's using highlightjs, with the not yet merged Tagger Script patch from https://github.com/isagalaev/highlight.js/pull/1103

It is a custom built version of highlightjs with only Tagger Script support enabled.

### CODE REVIEW

**Comment by mwiencek** [comment]
Awesome :)

**Comment by Freso** [comment]
Upstream did some changes to their taggerscript, so maybe a new PR to use what actually ended up in upstream (with relevant CSS adjustments)?

**Comment by phw** [comment]
@Freso: Did just that in PR #43. Also changed the coloring to look exactly as it does inside Picard. If you want that for Discourse and if we have the ability to include some custom CSS let me know and I'll give you the relevant CSS snippet.

**Comment by Freso** [comment]
Isn't it just website/frontend/static/less/highlightjs/picard.less? I don't see anything LESS-specific at a glance there. It'd be nice if it'd only apply to Tagger Script, but I guess that can be done by prepending all the declarations with `.taggerscript `. Too bad vanilla CSS doesn't support nesting. :)

**Comment by phw** [comment]
> Isn't it just website/frontend/static/less/highlightjs/picard.less?

Yes, without the basic `.hljs` rules (those are provided by the base theme) and `.lang-taggerscript` in front of each selector:

```css
.lang-taggerscript .hljs-comment {
  font-weight: bold;
  font-style: italic;
  color: #808080;
}

.lang-taggerscript .hljs-keyword {
  font-weight: bold;
  color: #0000FF;
}

.lang-taggerscript .hljs-variable {
  color: #008298;
}

.lang-taggerscript .hljs-symbol {
  color: #800000
}
```

It might look a bit out of place given the light colors discourse usually uses. Maybe instead of the bright blue `#0000FF` something less strong like `#2020C0`.

**Comment by jesus2099** [comment]
Superb, @phw! :clap::smile_cat:

**Pull request merged**
