### PR TITLE
Update font family to make website more readable

### PR DESCRIPTION
**Pull request by samj1912**
Comparison 

Before : 
image

After:
image

### CODE REVIEW

**Comment by mineo** [comment]
Note that Sintony is used by other MeB websites in the footer as well (at least AB, CB, MeB).

**Comment by samj1912** [comment]
Although it looks fine on mobile, it renders as above on my laptop. Maybe resolution problems?

**Comment by gentlecat** [comment]
@brainzbot, add to whitelist.

**Comment by phw** [comment]
> Although it looks fine on mobile, it renders as above on my laptop. Maybe resolution problems?

The font looks as ugly as on your first screenshot on my laptop, too (Firefox and Chrome on Linux / GNOME). I also checked on my Win 10 box, there it looks much better.

**Comment by Freso** [comment]
If we change it here, it should be changed for the rest of the MeB sites too, IMHO. We're working on unifying the sites' looks, so let's not introduce arbitrary site-specific aesthetic changes like this.

**Comment by Freso** [comment]
(Also, current looks fine on me on Firefox on Linux at 1080p, and I didn't notice issues at lower resolutions either.)

**Comment by samj1912** [comment]
@mwiencek @gentlecat any thoughts changing sintony across MeB?

**Comment by gentlecat** [comment]
@samj1912, not sure. I'll need to check other websites, but I also don't think that font has to be universal across all of our projects. Some might use slightly different styling and have different requirements.

If there's a problem with displaying of some of the fonts that we use, then that should be fixed.

**Comment by zas** [comment]
@Freso @phw @phw @mineo : merge or close ?

**Comment by samj1912** [comment]
Closing this since no consensus

**Pull request closed without merging**
