### PR TITLE
Include Fonts (roboto, sintony) Locally

### PR DESCRIPTION
**Pull request by nullHawk**
# Summary
Added roboto and sintony fonts locally which were previously loaded from google servers. As mentioned by @phw 
>This should be changed so the font files are part of the project and not loaded from third party servers. I think we could make the necessary font files part of the picard-website repository.

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [x] Other

# Problem

* JIRA ticket (_optional_): [PW-99](https://tickets.metabrainz.org/browse/PW-99)

# Solution

Added fonts locally inside fonts folder and created fonts.less in theme folder to load the fonts.

# Action

### CODE REVIEW

**Comment by zas** [comment]
Can you make the PR's title more explicit please?

**Comment by nullHawk** [comment]
> Can you make the PR's title more explicit please?

Sure

**Review by phw — APPROVED** [review]
Thanks for this. This looks very complete. Currently we don't need all those scripts included, but as I understand it the browser will only download those files with required unicode ranges, right?

**Comment by nullHawk** [comment]
> Thanks for this. This looks very complete. Currently we don't need all those scripts included, but as I understand it the browser will only download those files with required unicode ranges, right?

Thank you for your feedback. Yes, you're correct. The browser will only load the specific font files that contain the required unicode ranges defined in the unicode-range property.

**Review by zas — APPROVED** [review]
LGTM

**Pull request merged**
