### PR TITLE
PW-16: Move guide to the index and update Screenshots.

### PR DESCRIPTION
**Pull request by samj1912**
https://tickets.metabrainz.org/browse/PW-16

### CODE REVIEW

**Comment by samj1912** [comment]
@brainzbot , ok to test.

**Comment by samj1912** [comment]
image
Updated.

**Comment by zas** [comment]
:+1: looks ok to me

**Comment by samj1912** [comment]
Ah wait a quick look at the screenshot tells me I am not setting quick start guide to be active in the nav bar.

**Comment by samj1912** [comment]
image

Full page screen capture of the same

**Comment by gentlecat** [comment]
You should test the changes before merging them.

**Comment by zas** [comment]
> You should test the changes before merging them. https://ci.metabrainz.org/job/picard-website/22/

Oooops, we reallly need to fix "pending" issue

@samj1912 : can you fix so tests pass ?

**Comment by gentlecat** [comment]
The problem is that pull request wasn't tested. You need to allow testing manually or add contributors to a whitelist.

**Pull request merged**
